name: sport_team_manager
description: A sport team manager app
version: 0.0.1+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 1.0.4
  google_fonts: 2.2.0
  font_awesome_flutter: 9.2.0
  lottie: 1.2.1
  json_annotation: 4.4.0
  logger: 1.1.0
  flutter_riverpod: 1.0.3
  shared_preferences: 2.0.12
  url_launcher: 6.0.18
  fluttertoast: ^8.0.7
  cached_network_image: ^3.0.0
  file_picker: ^3.0.2+2
  image_picker: ^0.8.4+8
  firebase_storage: ^8.1.0


  #FIREBASE
  firebase_core: 1.11.0
  firebase_auth: 3.3.5
  cloud_firestore: 3.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4
  build_runner: 2.1.7  # https://pub.dev/packages/build_runner
  json_serializable: 6.1.4 # https://pub.dev/packages/json_serializable


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
